# Site title and subtitle. This is used in _includes/header.html
title: 'MacGap'
subtitle: 'Desktop WebKit wrapper for HTML/CSS/JS applications.'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://macgapproject.github.io/documentation/'

# Default categories (in order) to appear in the navigation
sections: [
    ['doc', 'Documentation'],
    ['tut', 'Tutorial'],
    ['ref', 'Command Reference'],
    ['dev', 'Developers'],
    ['post', 'Posts']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/documentation'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: 'rouge'

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']
